name: Deploy to Koyeb via GHCR

on:
  push:
    branches:
      - "release/staging/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.9

      - name: Build binary
        run: |
          go build -o server .

      - name: Build and push Docker image to GHCR
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_NAME=ghcr.io/thera-data-solution/thera-api:latest
          echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: |
          IMAGE_NAME=ghcr.io/thera-data-solution/thera-api:latest
          curl -X POST https://app.koyeb.com/v1/services/04d1dace-9cf1-4d72-bf66-176e3c771b9a/redeploy \
            -H "Authorization: Bearer $KOYEB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"deployment_group":"","sha":"","use_cache":false,"skip_build": false}'
